### ISSUE TITLE
Various undefined errors in PopupHandler and BackgroundMessage

### ISSUE THREAD

**Issue by marissajliu** [marissajliu/Neutral#23]
Loaded our package into Chrome Extensions, tried to use the extension on a product page, and got this error. 

Screenshots below:
<img width="680" alt="Screen Shot 2020-04-14 at 2 51 53 PM" src="https://user-images.githubusercontent.com/37420400/79262578-8c5b2d80-7e5f-11ea-9a65-0ddfcf6fec99.png">
<img width="679" alt="Screen Shot 2020-04-14 at 2 51 45 PM" src="https://user-images.githubusercontent.com/37420400/79262579-8cf3c400-7e5f-11ea-9156-422bde82d7ce.png">
<img width="721" alt="Screen Shot 2020-04-14 at 2 51 40 PM" src="https://user-images.githubusercontent.com/37420400/79262580-8d8c5a80-7e5f-11ea-9025-040b0cb17e64.png">
<img width="718" alt="Screen Shot 2020-04-14 at 2 51 32 PM" src="https://user-images.githubusercontent.com/37420400/79262581-8d8c5a80-7e5f-11ea-9299-73433768a162.png">
<img width="734" alt="Screen Shot 2020-04-14 at 2 51 28 PM" src="https://user-images.githubusercontent.com/37420400/79262582-8d8c5a80-7e5f-11ea-887f-f6ec3616a7d1.png">

Seems to be an error with the localstorage

**Comment by zharry** [comment]
Everything but the second screenshot should be showing a relatively similar error. Can you take a look at your localstorage? 
```
chrome.storage.local.get("amazon_product_info", console.log)
```
![image](https://user-images.githubusercontent.com/7399478/79274875-38f2da80-7e73-11ea-8b52-d951cfc09f80.png)

The second screenshot is telling me that the Initializer script is not running, as the API_GOOGLE_NLP localstorage key is not set. Can you take a look for that like this: 
```
chrome.storage.local.get("API_GOOGLE_NLP", console.log)
```

**Comment by marissajliu** [comment]
![Screen Shot 2020-04-21 at 11 04 10 AM](https://user-images.githubusercontent.com/37420400/79881922-d728f800-83bf-11ea-83a9-9d0b1089e1b0.png)
![Screen Shot 2020-04-21 at 11 04 43 AM](https://user-images.githubusercontent.com/37420400/79881984-e9a33180-83bf-11ea-94ba-47cfd8ca4d9e.png)
